# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: strain_seq-1.0.0
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  ## conda-forge packages
  - conda-forge::numpy>=1.24
  - conda-forge::python>=3.9,<3.12
  - conda-forge::gawk>=5.1
  - conda-forge::pigz>=2.6
  - conda-forge::textwrap3>=0.9
  - conda-forge::pandas>=2.0
  - conda-forge::r-base>=4.2
  - conda-forge::r-matrixstats>=0.63
  - conda-forge::r-optparse>=1.7
  - conda-forge::r-pheatmap>=1.0
  - conda-forge::r-rcolorbrewer>=1.1
  - conda-forge::r-reshape2>=1.4
  - conda-forge::r-scales>=1.2
  - conda-forge::r-tidyverse>=2.0
  - conda-forge::r-umap>=0.2

  ## bioconda packages
  - bioconda::fastqc>=0.12
  - bioconda::trim-galore>=0.6
  - bioconda::kallisto>=0.48
  - bioconda::bioconductor-edger>=3.42
  - bioconda::bioconductor-deseq2>=1.40
  - bioconda::pyfaidx>=0.7
  - bioconda::multiqc>=1.15
